"""Configuration values for fatigue detection thresholds."""

EYE_ASPECT_RATIO_THRESHOLD = 0.22
EYE_CLOSED_SECONDS_THRESHOLD = 1.2

BLINK_WINDOW_SECONDS = 60
BLINK_FREQUENCY_THRESHOLD = 18

MOUTH_OPEN_RATIO_THRESHOLD = 0.55
YAWN_SECONDS_THRESHOLD = 1.0
YAWN_COUNT_SCORE_THRESHOLD = 5

HEAD_NOD_DELTA_THRESHOLD = 0.09
HEAD_NOD_REBOUND_THRESHOLD = 0.035
HEAD_NOD_WINDOW_SECONDS = 1.8
HEAD_NOD_COOLDOWN_SECONDS = 1.2
HEAD_NOD_COUNT_ALERT_THRESHOLD = 3

EYE_CLOSURE_COUNT_WEIGHT = 8
YAWN_COUNT_WEIGHT = 10
HEAD_NOD_COUNT_WEIGHT = 15

FATIGUE_ALERT_THRESHOLD = 85

FRAME_PROCESSING_WIDTH = 640
